# Generated by Django 4.0.1 on 2022-07-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='creator',
            new_name='creator1',
        ),
    ]
